######################################################################
# Automatically generated by qmake (2.01a) Fr Nov 4 11:34:02 2011
######################################################################

TEMPLATE = app
TARGET = fileclean
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp mainwindow.cpp compare.cpp
HEADERS += mainwindow.h compare.h
FORMS += mainwindow.ui

QT += gui